pipeline {
    agent any 

    stages { 
        stage('SCM Checkout') {
            steps {
                retry(3) {
                    // Pull the latest code from the GitHub repository
                    git branch: 'main', url: 'https://github.com/Thisarak943/DockerJenkinsProject.git'
                }
            }
        }
        
        stage('Build Docker Image') {
            steps {  
                // Use the correct format for Windows environment variables
                bat 'docker build -t thisarakandage/nodeapp2:%BUILD_NUMBER% .'
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'test-dockerhubpassword', variable: 'test-dockerhubpass')]) {
                    // Login to Docker Hub using Jenkins credentials
                    bat 'docker login -u thisarakandage -p %test-dockerhubpass%'            
                }
            }
        }

        stage('Push Image') {
            steps {
                // Push the image to Docker Hub with a unique tag based on build number
                bat 'docker push thisarakandage/nodeapp2:%BUILD_NUMBER%'
            }
        }
    }

    post {
        always {
            // Logout from Docker Hub to ensure security
            bat 'docker logout'
        }
    }
}
